# Generated by Django 5.0.4 on 2024-05-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='appoinment',
        ),
    ]
