# Generated by Django 5.0.4 on 2024-05-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_booking_appoinment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appoinment',
            new_name='Appointment',
        ),
    ]
